### PR TITLE
Replace Http with HttpClient

### PR DESCRIPTION
**Pull request by sebaiona**
@kneefer Is there a chance of an update where you replace Http with HttpClient ?

### CODE REVIEW

**Comment by kneefer** [comment]
@sebaiona  Are you sure you wanted to create this PR under `ngx-translate-po-http-loader`?
I never meant to merge my fork `ngx-translate-resx-http-loader` to this repo since its functionality is totally different (po != resx files).

**Comment by sebaiona** [comment]
@kneefer this is not what I wanted to do at all.
I did it too quickly... 

I wanted to ask you if you were going to replace Http by HttpClient in your fork `ngx-translate-resx-http-loader`

**Comment by kneefer** [comment]
@sebaiona Yeah. No problem. I will do it on Thursday :)

**Comment by sebaiona** [comment]
@kneefer Thanks !
Let me know when it's done and I will test it !

**Comment by kneefer** [comment]
@sebaiona Done. 
Performed basic smoke tests - everything seems working but I will appreciate if you confirm ;)

@biesbjerg Sorry for spam under your repo. I believe you can reject this PR now.

**Comment by sebaiona** [comment]
Everything seems to work fine !
Thank you @kneefer !!

And sorry @biesbjerg  for the spam... 
My bad...

**Pull request closed without merging**
